# Generated by Django 3.1.2 on 2020-10-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_color_enemy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spell',
            name='color',
        ),
        migrations.AddField(
            model_name='color',
            name='spells',
            field=models.ManyToManyField(to='api.Spell'),
        ),
    ]
