# Generated by Django 3.1.2 on 2020-10-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201011_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
