# Generated by Django 3.1.2 on 2020-10-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0002_remove_color_spells'),
        ('spell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='colors',
            field=models.ManyToManyField(to='color.Color'),
        ),
    ]
