# Generated by Django 3.1.2 on 2020-10-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0003_enemy_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='xp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='mana',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
