# Generated by Django 3.1.2 on 2020-10-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spell', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hexa', models.CharField(max_length=200)),
                ('spells', models.ManyToManyField(to='spell.Spell')),
            ],
        ),
    ]
