# Generated by Django 3.1.2 on 2020-10-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='uploads/')),
                ('sound', models.FileField(default='', upload_to='uploads/')),
            ],
        ),
    ]
