# Generated by Django 3.1.2 on 2020-10-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_auto_20201020_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='damage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
