# Generated by Django 3.1.2 on 2020-10-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_player_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='currentXP',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
